
services:

    admin.category:
        class: AppBundle\Admin\CategoryAdmin
        arguments: [~, AppBundle\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Category }
        public: true

    admin.podcast:
        class: AppBundle\Admin\PodcastAdmin
        arguments: [~, AppBundle\Entity\Podcast, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Podcast }
        public: true